package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ============================================================================
// Chapter 6 Hands-On: End-to-End Implementation
// FILE: api/v1/appservice_types.go
// ============================================================================
// Here we define the strongly typed Go structs that represent our Custom Resource.
// In a true production environment, these files live in `api/v1/` and are used
// by controller-gen to produce the YAML CRDs.
// ============================================================================

var GroupVersion = schema.GroupVersion{Group: "webapp.mydomain.com", Version: "v1"}
var SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)
var AddToScheme = SchemeBuilder.AddToScheme

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(GroupVersion, &AppService{}, &AppServiceList{})
	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
}

// AppServiceSpec defines the desired state (Input).
type AppServiceSpec struct {
	Replicas int32  `json:"replicas"`
	Image    string `json:"image"`
	Port     int32  `json:"port"`
}

// AppServiceStatus defines the observed state (Output).
type AppServiceStatus struct {
	AvailableReplicas int32  `json:"availableReplicas"`
	Phase             string `json:"phase,omitempty"`
}

// AppService is the Schema for the appservices API.
type AppService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AppServiceSpec   `json:"spec,omitempty"`
	Status            AppServiceStatus `json:"status,omitempty"`
}

func (in *AppService) DeepCopyObject() runtime.Object { return in }

// AppServiceList contains a list of AppService.
type AppServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AppService `json:"items"`
}

func (in *AppServiceList) DeepCopyObject() runtime.Object { return in }

// Boilerplate deepcopy methods (usually autogenerated).
func (in *AppService) DeepCopyInto(out *AppService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *AppService) DeepCopy() *AppService {
	if in == nil {
		return nil
	}
	out := new(AppService)
	in.DeepCopyInto(out)
	return out
}

func (in *AppServiceList) DeepCopyInto(out *AppServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppServiceList) DeepCopy() *AppServiceList {
	if in == nil {
		return nil
	}
	out := new(AppServiceList)
	in.DeepCopyInto(out)
	return out
}
